language: php

services:
  - mysql
php:
  - 5.6

before_install:
  - cp ./config/database.travis.php ./config/database.php
  - composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master
  - composer install --dev --ignore-platform-reqs
  - mysql -e 'CREATE DATABASE account;'
  - mysql -u root  account < ./sql/registrationModule.sql

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v